id = "core-language"
name = "Core Language"
version = "0.1.0"
schema_version = 1
authors = ["DslsDZC"]
description = "Core programming language support — syntax highlighting"
repository = "https://github.com/dslsdzc/core"

[grammars.core]
repository = "https://github.com/dslsdzc/core-plugin-zed"
rev = "4a22ed4c7faa9e8b4ed2e62526699ee1f78516bf"
