id = "core-language"
name = "Core Language"
version = "0.1.0"
schema_version = 1
authors = ["DslsDZC"]
description = "Core programming language support — syntax highlighting"
repository = "https://github.com/dslsdzc/core"

[grammars.core]
repository = "https://github.com/dslsdzc/core-plugin-zed"
rev = "c02489e3eed8d4e96e66a10b473018104c252a38"
